"""Repository registry, deterministic release configuration and scaffolding."""
from __future__ import annotations

from pathlib import Path
import re
import shutil
from typing import Any

from .common import (
    ToolError, atomic_write, json_text, load_json, mutation_lock, require,
    rollback_files, slug, stable_version, validate_schema, write_json,
)

DRAFT_MARKER = "SCAFFOLD:NOT_READY"
VERSION_MARKER = "x-release-please-version"


def settings(root: Path) -> dict:
    value = load_json(root / "repository.json")
    validate_schema(root, "repository", value, "repository.json")
    return value


def registry(root: Path) -> list[dict]:
    result = []
    seen: set[str] = set()
    for path in sorted((root / "catalog").glob("*.json")):
        require(not path.is_symlink(), f"Symlink not allowed: {path}")
        value = load_json(path)
        validate_schema(root, "skill", value, str(path.relative_to(root)))
        require(value["name"] == path.stem, f"Registry filename differs from name: {path}")
        require(value["name"] not in seen, f"Duplicate skill: {value['name']}")
        seen.add(value["name"])
        result.append(value)
    return result


def entry(root: Path, name: str) -> dict:
    slug(name)
    value = load_json(root / "catalog" / f"{name}.json")
    validate_schema(root, "skill", value, f"catalog/{name}.json")
    require(value["name"] == name, "Registry filename/name mismatch.")
    return value


def skill_version(root: Path, name: str) -> str:
    return stable_version((root / "skills" / slug(name) / "version.txt").read_text(encoding="utf-8").strip())


def expected_release_config(root: Path) -> dict:
    entries = registry(root)
    packages: dict[str, Any] = {
        ".": {
            "release-type": "simple",
            "package-name": "agent-skills-catalog",
            "include-component-in-tag": False,
            "version-file": "version.txt",
            "changelog-path": "CHANGELOG.md",
            "exclude-paths": [f"skills/{item['name']}" for item in entries if item["status"] == "draft"],
        }
    }
    for item in entries:
        if item["status"] != "active":
            continue
        name = item["name"]
        packages[f"skills/{name}"] = {
            "release-type": "simple",
            "package-name": name,
            "component": name,
            "version-file": "version.txt",
            "changelog-path": "CHANGELOG.md",
            "skip-github-release": True,
            "extra-files": [{"type": "generic", "path": "SKILL.md"}],
        }
    return {
        "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
        "separate-pull-requests": False,
        "bump-minor-pre-major": True,
        "bump-patch-for-minor-pre-major": False,
        "packages": packages,
    }


def sync_release_config(root: Path) -> None:
    """Regenerate paths; never silently reset any existing release version."""
    expected = expected_release_config(root)
    old = load_json(root / ".release-please-manifest.json")
    require(isinstance(old, dict), "Release manifest must be an object.")
    stale = set(old) - set(expected["packages"])
    require(not stale, f"Released/registered components removed: {sorted(stale)}. Plan deprecation explicitly.")
    manifest = {}
    for path in expected["packages"]:
        current = stable_version((root / path / "version.txt").read_text(encoding="utf-8").strip())
        if path in old:
            require(old[path] == current,
                    f"Version mismatch at {path}: manifest={old[path]}, version.txt={current}. Do not reset a release.")
            manifest[path] = old[path]
        else:
            require(current == "0.0.0", f"New component must bootstrap at 0.0.0: {path}")
            manifest[path] = "0.0.0"
    write_json(root / "release-please-config.json", expected)
    write_json(root / ".release-please-manifest.json", manifest)


def render_catalog(root: Path) -> str:
    config = settings(root)
    lines = ["# Skill catalog", "", "Generated by `make catalog-update`. Do not edit manually.", "",
             "| Skill | Status | Content |", "| --- | --- | --- |"]
    for item in registry(root):
        name = item["name"]
        filename = "SKILL.md" if item["status"] == "active" else "SKILL.md.template"
        status = "Active" if item["status"] == "active" else "Draft - not installable"
        lines.append(f"| {item['display_name']} (`{name}`) | {status} | [Source](../skills/{name}/{filename}) |")
    lines += ["", "Versions are recorded in each skill's `version.txt` and `metadata.version`.",
              "Each release index records the exact component versions and payload checksums.", ""]
    active = [item for item in registry(root) if item["status"] == "active"]
    if config["github"] and active:
        lines += ["## Install from the default branch", "", "```bash"]
        lines += [f"npx skills add {config['github']} --skill {item['name']}" for item in active]
        lines += ["```", "", "These commands follow the default branch, not a fixed SemVer release.", ""]
    return "\n".join(lines)


def draft_text(name: str, display_name: str) -> str:
    return f'''---
name: {name}
description: >-
  Reserved draft of {display_name}. Do not use for real tasks until the
  maintainer defines and validates its scope, activation triggers, and instructions.
license: MIT
metadata:
  version: "0.0.0" # {VERSION_MARKER}
---

# {display_name}

<!-- {DRAFT_MARKER} -->

This is a skill scaffold, not an implemented capability.
Do not invent workflows, mandatory tools, dependencies, or evaluation results.

## Scope and activation triggers

TODO: Define what the skill does, when it should activate, and when it should not.
Include the essential activation triggers in `description` before activation.

## Instructions

TODO: Add the actual procedure, required inputs, and authority boundaries.

## Outputs and completion criteria

TODO: Define the output contract and observable success criteria.

## Resources

Include only user-facing resources in `scripts/`, `references/`, and `assets/`.
Use relative links to existing files; do not depend on the monorepo root.
'''


def new_skill(root: Path, name: str, display_name: str | None = None) -> None:
    name = slug(name)
    display_name = display_name or name.replace("-", " ").title()
    item = {"schema_version": 1, "name": name, "display_name": display_name,
            "status": "draft", "entrypoints": [], "smoke_tests": []}
    validate_schema(root, "skill", item, "new skill")
    config_path = root / "catalog" / f"{name}.json"
    skill_dir = root / "skills" / name
    test_dir = root / "tests" / "skills" / name
    require(not any(path.exists() for path in (config_path, skill_dir, test_dir)), f"Skill already exists: {name}")
    with mutation_lock(root), rollback_files([config_path, root / "release-please-config.json",
                                             root / ".release-please-manifest.json", root / "docs/CATALOG.md"]):
        try:
            skill_dir.mkdir(parents=True)
            test_dir.mkdir(parents=True)
            atomic_write(skill_dir / "SKILL.md.template", draft_text(name, display_name))
            atomic_write(skill_dir / "version.txt", "0.0.0\n")
            atomic_write(skill_dir / "CHANGELOG.md", "# Changelog\n\nNot released yet.\n")
            shutil.copyfile(root / "LICENSE", skill_dir / "LICENSE")
            for directory in ("scripts", "references", "assets"):
                atomic_write(skill_dir / directory / ".gitkeep", "")
            write_json(config_path, item)
            write_json(test_dir / "evals.json", {
                "schema_version": 1, "skill": name,
                "review": {"status": "pending", "evidence": "", "payload_sha256": ""}, "cases": [],
            })
            atomic_write(test_dir / "README.md", f'''# {display_name} evaluations

Add at least one positive and one negative activation case to `evals.json`.
Run the cases in the target agent and record actual evidence in `review.evidence`.
Set `review.status` to `approved` only after human review. Record the current
payload fingerprint with `make skill-fingerprint NAME={name}`; changed content requires
new evidence, not merely a new fingerprint.

Repository checks validate the evaluation contract; they do not run or simulate an LLM.
Script smoke tests are defined in `catalog/{name}.json` and run against a copied
skill without importing files from the repository root.
''')
            sync_release_config(root)
            atomic_write(root / "docs/CATALOG.md", render_catalog(root))
        except Exception:
            shutil.rmtree(skill_dir, ignore_errors=True)
            shutil.rmtree(test_dir, ignore_errors=True)
            raise


def activate_skill(root: Path, name: str) -> None:
    """Explicit promotion, after readiness checks; a failed promotion rolls back."""
    from .validation import validate_skill
    from .isolation import isolate_skill
    item = entry(root, name)
    require(item["status"] == "draft", f"Already active: {name}")
    source = root / "skills" / name / "SKILL.md.template"
    target = source.with_name("SKILL.md")
    require(source.is_file() and not target.exists(), "Expected exactly one SKILL.md.template.")
    changed = [source, target, root / "catalog" / f"{name}.json", root / "release-please-config.json",
               root / ".release-please-manifest.json", root / "docs/CATALOG.md"]
    with mutation_lock(root), rollback_files(changed):
        source.rename(target)
        item["status"] = "active"
        write_json(root / "catalog" / f"{name}.json", item)
        validate_skill(root, item)
        isolate_skill(root, item)
        sync_release_config(root)
        atomic_write(root / "docs/CATALOG.md", render_catalog(root))


def configure(root: Path, github: str, codeowner: str | None = None) -> None:
    config = settings(root)
    config["github"] = github
    validate_schema(root, "repository", config, "repository.json")
    if codeowner:
        require(re.fullmatch(r"@[A-Za-z0-9][A-Za-z0-9-]*(?:/[A-Za-z0-9_.-]+)?", codeowner),
                "CODEOWNER must be @username or @org/team.")
    with mutation_lock(root), rollback_files([root / "repository.json", root / "docs/CATALOG.md", root / ".github/CODEOWNERS"]):
        write_json(root / "repository.json", config)
        atomic_write(root / "docs/CATALOG.md", render_catalog(root))
        if codeowner:
            atomic_write(root / ".github/CODEOWNERS", f"# Ownership is enforced only when a GitHub ruleset requires it.\n* {codeowner}\n")
